# Generated by Django 6.1 on 2026-08-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TRD Examination', max_length=200)),
                ('number_of_questions', models.PositiveIntegerField(default=20)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('pass_percentage', models.PositiveIntegerField(default=40)),
                ('negative_marking', models.BooleanField(default=False)),
                ('negative_marks', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Question')),
                ('option_a', models.CharField(max_length=500, verbose_name='Option A')),
                ('option_b', models.CharField(max_length=500, verbose_name='Option B')),
                ('option_c', models.CharField(max_length=500, verbose_name='Option C')),
                ('option_d', models.CharField(max_length=500, verbose_name='Option D')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Correct Answer')),
                ('explanation', models.TextField(blank=True, verbose_name='Explanation')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
